// Package harbor is the real registry.Manager + registry.Querier: a thin net/http client against
// Harbor's /api/v2.0 REST API (the same shape as internal/netbox and internal/vault/hcvault). It is
// built only where a credential lives - the WORKER (the admin credential, driving
// EnsurePlatform/EnsureCluster/ReleaseCluster/SyncAccess) and the API (a read-only robot, calling
// only the Querier half). Every write is an idempotent upsert, so it is safe to re-run on every
// reconcile tick and every SyncAccess sweep.
//
// Shortcuts, in the repo's style (documented rather than hidden):
//   - The API is given a read-only system robot through the environment rather than one minted and
//     handed over by the worker. Production would provision it out of band (or federate both
//     processes behind an IdP) so no long-lived credential sits in two env files.
//   - Local-mode user passwords are generated by the platform, applied here, and shown to their owner
//     once. Production would run OIDC in front of both the portal and Harbor so no password is
//     generated, copied or displayed at all.
//   - A robot is minted with a long TTL and never rotated. The expiry is recorded on the cluster row
//     (Cluster.RegistryRobotNotAfter) so a rotation sweep can be added as a time-driven due-scan,
//     exactly like certificate renewal.
package harbor

import (
	"bytes"
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"net/url"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/Daniel-Vaz/KaaS-demo/internal/domain"
	"github.com/Daniel-Vaz/KaaS-demo/internal/events"
	"github.com/Daniel-Vaz/KaaS-demo/internal/registry"
)

// Config builds a Client.
type Config struct {
	Settings registry.Settings
	Events   events.Sink
	Log      *slog.Logger
}

// Client is the real registry seam.
type Client struct {
	base string
	set  registry.Settings
	user string
	pass string
	http *http.Client
	ev   events.Sink
	log  *slog.Logger

	// mu guards the cached status, which is read on every Registry page load and would otherwise put
	// a health round-trip on the critical path of every request.
	mu       sync.Mutex
	status   registry.Status
	statusAt time.Time
}

// statusTTL bounds how stale the cached health may be. A registry that has just come back should
// stop being reported as down promptly, but not at the cost of a round-trip per page load.
const statusTTL = 20 * time.Second

// New builds a Client from validated settings.
func New(cfg Config) (*Client, error) {
	s, err := cfg.Settings.Validate()
	if err != nil {
		return nil, err
	}
	if !s.Enabled() {
		return nil, fmt.Errorf("harbor: KAAS_REGISTRY_URL is required")
	}
	tr := &http.Transport{}
	if s.Insecure {
		tr.TLSClientConfig = &tls.Config{InsecureSkipVerify: true}
	}
	return &Client{
		base: strings.TrimRight(s.URL, "/") + "/api/v2.0",
		set:  s,
		user: s.Username,
		pass: s.Password,
		http: &http.Client{Timeout: 30 * time.Second, Transport: tr},
		ev:   cfg.Events,
		log:  cfg.Log,
	}, nil
}

// do performs one Harbor API call. okCodes are statuses treated as success besides 2xx - Harbor
// answers "already exists" with 409 on nearly every create, which is exactly what an idempotent
// upsert wants to ignore.
func (c *Client) do(ctx context.Context, method, path string, body, out any, okCodes ...int) error {
	var rdr io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return err
		}
		rdr = bytes.NewReader(b)
	}
	req, err := http.NewRequestWithContext(ctx, method, c.base+path, rdr)
	if err != nil {
		return err
	}
	req.SetBasicAuth(c.user, c.pass)
	req.Header.Set("Accept", "application/json")
	if body != nil {
		req.Header.Set("Content-Type", "application/json")
	}
	resp, err := c.http.Do(req)
	if err != nil {
		return fmt.Errorf("harbor: %s %s: %w", method, path, err)
	}
	defer resp.Body.Close()
	data, _ := io.ReadAll(io.LimitReader(resp.Body, 4<<20))
	if resp.StatusCode >= 200 && resp.StatusCode < 300 {
		if out != nil && len(data) > 0 {
			return json.Unmarshal(data, out)
		}
		return nil
	}
	for _, ok := range okCodes {
		if resp.StatusCode == ok {
			return nil
		}
	}
	return fmt.Errorf("harbor: %s %s: %d: %s", method, path, resp.StatusCode, strings.TrimSpace(string(data)))
}

// emit puts a message on a CLUSTER's activity timeline, or logs it when the message is
// platform-scoped. The split is forced by the schema exactly as it is in hcvault: events.cluster_id
// is NOT NULL and foreign-keyed, so an emit with no cluster id is a guaranteed FK violation that
// surfaces as a database error rather than a dropped log line.
func (c *Client) emit(clusterID, level, msg string) {
	if clusterID == "" {
		if c.log != nil {
			if level == "warn" {
				c.log.Warn(msg)
			} else {
				c.log.Info(msg)
			}
		}
		return
	}
	if c.ev != nil {
		c.ev.Emit(events.Event{ClusterID: clusterID, Source: "registry", Level: level, Message: msg})
	}
}

// --- Manager ---------------------------------------------------------------------------------

// EnsurePlatform provisions everything that is not per-cluster: the auth backend mirroring the
// portal, the library project, one proxy-cache project (and its upstream registry endpoint) per
// mirrored host, and the garbage-collection schedule that stops the cache growing without bound.
//
// It mints NO credential. The cache and library projects are PUBLIC, so a cluster node pulls
// through them anonymously and no fleet-wide secret ever lands on a tenant's VM - see
// registry.NodeTrust for why that is the right trade and what it costs. Idempotent throughout: a 409
// "already exists" is success.
func (c *Client) EnsurePlatform(ctx context.Context) error {
	// Auth is NOT configured here - see registry.Manager.EnsureAuth. This runs on the worker, which
	// has no directory settings, so it would only ever no-op.
	//
	// Public: a node pulls the platform's own images with no credential at all.
	if err := c.ensureProject(ctx, c.set.Library(), true, 0, ""); err != nil {
		return err
	}
	if c.set.Mirror {
		// Per-upstream failures are logged and STEPPED OVER rather than returned. Each cache is an
		// independent optimisation for one upstream, and every hosts.toml keeps the upstream as its
		// `server` fallback - so a cache that cannot be created costs pull speed for that one
		// registry. Returning here instead made a single unsupported provider type abort the whole
		// platform bootstrap: the caches after it, the GC schedule, and - because the reconciler
		// retries the same failing call forever - every per-cluster project too. One upstream Harbor
		// dislikes must not cost the tenant registry.
		for _, u := range c.set.Upstreams {
			id, err := c.ensureUpstream(ctx, u)
			if err != nil {
				c.emit("", "warn", fmt.Sprintf("registry: could not register the %s upstream, so it will not be cached (nodes still pull it directly): %v", u.Name, err))
				continue
			}
			// Public, for the reason above: the contents are public upstream images, and making a
			// node authenticate to reach them would buy nothing and cost a fleet credential.
			if err := c.ensureProject(ctx, c.set.CacheProject(u), true, 0, strconv.FormatInt(id, 10)); err != nil {
				c.emit("", "warn", fmt.Sprintf("registry: could not create the %s cache project (nodes still pull it directly): %v", u.Name, err))
			}
		}
	}
	if err := c.ensureGCSchedule(ctx); err != nil {
		// Not fatal: the registry works, it just needs manual housekeeping. Say so rather than
		// failing platform setup over a cleanup schedule.
		c.emit("", "warn", "registry: could not set the garbage-collection schedule: "+err.Error())
	}
	c.emit("", "info", fmt.Sprintf("registry: provisioned the platform projects at %s (mirror=%v)", c.set.Host, c.set.Mirror))
	return nil
}

// EnsureAuth points Harbor at the same identity source the portal uses. In ldap mode it writes the
// same directory settings the portal and Vault read from the mounted ldap.yaml, so a user's one set
// of credentials works in all three. Self-registration is turned off in both modes: the platform is
// the only way an account comes into existence.
func (c *Client) EnsureAuth(ctx context.Context) error {
	if !c.set.ManageAuth {
		// This process cannot see the directory configuration, so it has no authoritative view of how
		// the registry should authenticate - see registry.Settings.ManageAuth. Writing the fallback
		// would lock every user out.
		c.emit("", "info", "registry: leaving the registry's authentication configuration untouched (no directory config in this process)")
		return nil
	}
	cfg := map[string]any{
		"self_registration":            false,
		"project_creation_restriction": "adminonly",
	}
	switch c.set.AuthMode {
	case registry.AuthLDAP:
		l := c.set.LDAP
		cfg["auth_mode"] = "ldap_auth"
		cfg["ldap_url"] = l.URL
		cfg["ldap_search_dn"] = l.BindDN
		cfg["ldap_search_password"] = l.BindPassword
		cfg["ldap_base_dn"] = l.BaseDN
		cfg["ldap_uid"] = l.UID
		cfg["ldap_verify_cert"] = l.VerifyCert
		cfg["ldap_scope"] = 2 // subtree
	default:
		cfg["auth_mode"] = "db_auth"
	}
	err := c.do(ctx, http.MethodPut, "/configurations", cfg, nil)
	if err == nil {
		c.emit("", "info", "registry: configured the registry's authentication ("+c.set.AuthMode+")")
		return nil
	}
	// Harbor refuses to change auth_mode once its own database holds any user, because switching
	// would orphan them - so this is not a transient failure and retrying never clears it. It is
	// worth naming precisely, since the state that causes it is usually invisible: a single local
	// account created before the mode was set is enough, and the remedy is to delete those accounts
	// (the platform's own are recreated) rather than anything about this configuration.
	if strings.Contains(err.Error(), "auth mode cannot be modified") {
		return fmt.Errorf("%w - the registry already holds local accounts, and it will not change auth mode while any exist; delete them in the registry's Administration > Users and this will apply on the next start-up", err)
	}
	return err
}

// ensureUpstream registers (or updates) the remote registry a proxy-cache project pulls through, and
// returns its id. Docker Hub credentials matter here: an anonymous proxy inherits Docker Hub's
// anonymous rate limit for the WHOLE fleet, which is one of the failures this integration exists to
// remove.
func (c *Client) ensureUpstream(ctx context.Context, u registry.Upstream) (int64, error) {
	name := "kaas-" + u.Name
	body := map[string]any{
		"name":        name,
		"type":        u.Type,
		"url":         u.Endpoint,
		"insecure":    false,
		"description": "Managed by KubeHarbor - proxy cache upstream for " + u.Host,
	}
	if cred, ok := c.set.UpstreamAuth[u.Name]; ok && cred.Username != "" {
		body["credential"] = map[string]any{
			"type":          "basic",
			"access_key":    cred.Username,
			"access_secret": cred.Password,
		}
	}
	if err := c.do(ctx, http.MethodPost, "/registries", body, nil, http.StatusConflict); err != nil {
		return 0, err
	}
	var list []struct {
		ID   int64  `json:"id"`
		Name string `json:"name"`
	}
	if err := c.do(ctx, http.MethodGet, "/registries?q=name%3D"+url.QueryEscape(name)+"&page_size=100", nil, &list); err != nil {
		return 0, err
	}
	for _, r := range list {
		if r.Name == name {
			return r.ID, nil
		}
	}
	return 0, fmt.Errorf("harbor: upstream registry %q was neither created nor found", name)
}

// ensureProject creates a project if absent. registryID non-empty makes it a pull-through proxy of
// that upstream. Idempotent by way of the 409.
func (c *Client) ensureProject(ctx context.Context, name string, public bool, quotaGB int, registryID string) error {
	meta := map[string]string{"public": strconv.FormatBool(public)}
	if registryID == "" {
		// Scan on push and block the worst findings from being pulled. Only meaningful on a project
		// that receives pushes - a proxy cache mirrors whatever upstream holds.
		meta["auto_scan"] = "true"
	}
	body := map[string]any{"project_name": name, "metadata": meta}
	if registryID != "" {
		id, err := strconv.ParseInt(registryID, 10, 64)
		if err != nil {
			return err
		}
		body["registry_id"] = id
	}
	if quotaGB > 0 {
		body["storage_limit"] = int64(quotaGB) * 1024 * 1024 * 1024
	}
	return c.do(ctx, http.MethodPost, "/projects", body, nil, http.StatusConflict)
}

// ensureGCSchedule keeps the proxy cache from growing without bound. The registry lives on the same
// host whose capacity the platform's own quota is guarding, so untended cache growth is not a
// cosmetic problem: it competes with the VMs.
func (c *Client) ensureGCSchedule(ctx context.Context) error {
	body := map[string]any{
		"schedule":   map[string]any{"type": "Weekly", "cron": "0 0 3 * * 0"},
		"parameters": map[string]any{"delete_untagged": true},
	}
	// PUT replaces an existing schedule; POST creates the first one. Try the update, fall back.
	if err := c.do(ctx, http.MethodPut, "/system/gc/schedule", body, nil); err == nil {
		return nil
	}
	return c.do(ctx, http.MethodPost, "/system/gc/schedule", body, nil, http.StatusConflict)
}

// findRobot resolves a robot's id and full name (Harbor prefixes "robot$") from the short name.
func (c *Client) findRobot(ctx context.Context, short string) (int64, string, error) {
	var list []struct {
		ID   int64  `json:"id"`
		Name string `json:"name"`
	}
	if err := c.do(ctx, http.MethodGet, "/robots?page_size=100&q=name%3D"+url.QueryEscape(short), nil, &list); err != nil {
		return 0, "", err
	}
	for _, r := range list {
		if r.Name == short || r.Name == "robot$"+short {
			return r.ID, r.Name, nil
		}
	}
	return 0, "", fmt.Errorf("harbor: robot %q not found", short)
}

// EnsureCluster provisions the cluster's private project and its push+pull robot.
//
// The robot is minted ONCE. A re-run returns the existing identity with an EMPTY secret, and the
// caller keeps the credential it already sealed - because this credential is delivered to the
// cluster as a Kubernetes pull Secret, and silently rotating it on a level-triggered re-run would
// leave every pod in the cluster unable to pull until the next wiring pass. That is the opposite of
// the mirror robot's trade, where the value reaches nodes on the next playbook run anyway.
func (c *Client) EnsureCluster(ctx context.Context, cl *domain.Cluster) (registry.RobotCredential, error) {
	project := c.set.ClusterProject(cl)
	if err := c.ensureProject(ctx, project, false, c.set.ProjectQuotaGB, ""); err != nil {
		return registry.RobotCredential{}, err
	}
	short := registry.ClusterRobot(cl)
	body := map[string]any{
		"name":        short,
		"description": fmt.Sprintf("KubeHarbor: push/pull credential for cluster %q", cl.Name),
		"duration":    int(c.set.RobotTTL.Hours() / 24),
		"level":       "system",
		"permissions": []map[string]any{{
			"kind":      "project",
			"namespace": project,
			"access": []map[string]string{
				{"resource": "repository", "action": "pull"},
				{"resource": "repository", "action": "push"},
				{"resource": "artifact", "action": "read"},
				{"resource": "tag", "action": "list"},
			},
		}},
	}
	var created struct {
		Name   string `json:"name"`
		Secret string `json:"secret"`
	}
	err := c.do(ctx, http.MethodPost, "/robots", body, &created)
	if err == nil && created.Secret != "" {
		c.emit(cl.ID, "info", fmt.Sprintf("provisioned registry project %q and its push/pull robot", project))
		return registry.RobotCredential{Username: created.Name, Secret: created.Secret,
			Expires: time.Now().Add(c.set.RobotTTL)}, nil
	}
	if err != nil && !strings.Contains(err.Error(), "409") {
		return registry.RobotCredential{}, err
	}
	_, name, err := c.findRobot(ctx, short)
	if err != nil {
		return registry.RobotCredential{}, err
	}
	// Identity only, no secret: the caller keeps the one it sealed the first time.
	return registry.RobotCredential{Username: name}, nil
}

// ReleaseCluster removes the cluster's robot and project. Absence is success, so it is safe on every
// deleting tick and on a retry. RetainProject keeps the images and drops only the credential - the
// credential is scoped to a project nobody can reach any more, but it is still a live credential.
func (c *Client) ReleaseCluster(ctx context.Context, cl *domain.Cluster) error {
	if id, _, err := c.findRobot(ctx, registry.ClusterRobot(cl)); err == nil {
		if err := c.do(ctx, http.MethodDelete, "/robots/"+strconv.FormatInt(id, 10), nil, nil,
			http.StatusNotFound); err != nil {
			return err
		}
	}
	if c.set.RetainProject {
		c.emit(cl.ID, "info", fmt.Sprintf("retained registry project %q (KAAS_REGISTRY_RETAIN_PROJECT)", c.set.ClusterProject(cl)))
		return nil
	}
	project := c.set.ClusterProject(cl)
	// Harbor refuses to delete a project that still holds repositories, so drop those first. A
	// project the platform created for a cluster holds only that cluster's images.
	repos, err := c.repositories(ctx, project)
	if err == nil {
		for _, r := range repos {
			_ = c.do(ctx, http.MethodDelete,
				"/projects/"+url.PathEscape(project)+"/repositories/"+repoPath(r.Name), nil, nil,
				http.StatusNotFound)
		}
	}
	if err := c.do(ctx, http.MethodDelete, "/projects/"+url.PathEscape(project), nil, nil,
		http.StatusNotFound, http.StatusBadRequest); err != nil {
		return err
	}
	// The cluster row still exists here: releaseRegistry runs in PhaseDeleting, BEFORE DestroyCluster
	// and before the row is dropped - so the event's FK holds.
	c.emit(cl.ID, "info", fmt.Sprintf("released registry project %q", project))
	return nil
}

// SyncAccess converges accounts and project memberships to registry.DesiredAccess(snap).
//
// It is additive plus corrective on the rows the platform owns: every desired membership is applied
// at its role, and a membership on a platform-owned project that the platform did not intend is
// removed. It deliberately does NOT touch projects it does not own (KindExternal), so a Harbor
// already used for other work keeps its own memberships.
func (c *Client) SyncAccess(ctx context.Context, snap registry.AccessSnapshot) error {
	desired := registry.DesiredAccess(snap, c.set)

	if c.set.AuthMode == registry.AuthLocal {
		for _, u := range desired.Users {
			if err := c.ensureLocalUser(ctx, u); err != nil {
				return err
			}
		}
	}
	for _, u := range desired.Users {
		if err := c.ensureSysAdmin(ctx, u); err != nil {
			// A user who has never logged in does not exist in ldap mode, which is ordinary rather
			// than exceptional - the flag lands on their next sweep after their first login.
			c.log.Debug("registry: could not set system-admin flag", "user", u.Username, "err", err)
		}
	}

	// Group the desired memberships by project so each project is read once.
	byProject := map[string][]registry.DesiredMember{}
	for _, m := range desired.Members {
		byProject[m.Project] = append(byProject[m.Project], m)
	}
	for project, want := range byProject {
		if err := c.syncProjectMembers(ctx, project, want); err != nil {
			return err
		}
	}
	return nil
}

// syncProjectMembers converges one project's membership list.
func (c *Client) syncProjectMembers(ctx context.Context, project string, want []registry.DesiredMember) error {
	type memberRow struct {
		ID     int64  `json:"id"`
		Name   string `json:"entity_name"`
		RoleID int    `json:"role_id"`
		Type   string `json:"entity_type"`
	}
	var have []memberRow
	if err := c.do(ctx, http.MethodGet,
		"/projects/"+url.PathEscape(project)+"/members?page_size=100", nil, &have,
		http.StatusNotFound); err != nil {
		return err
	}
	haveByName := map[string]memberRow{}
	for _, m := range have {
		haveByName[strings.ToLower(m.Name)] = m
	}
	wantByName := map[string]registry.DesiredMember{}
	for _, m := range want {
		wantByName[m.Username] = m
	}

	for _, m := range want {
		roleID := roleID(m.Role)
		existing, ok := haveByName[m.Username]
		switch {
		case !ok:
			body := map[string]any{
				"role_id":     roleID,
				"member_user": map[string]string{"username": m.Username},
			}
			if err := c.do(ctx, http.MethodPost,
				"/projects/"+url.PathEscape(project)+"/members", body, nil,
				http.StatusConflict, http.StatusNotFound, http.StatusBadRequest); err != nil {
				return err
			}
		case existing.RoleID != roleID:
			if err := c.do(ctx, http.MethodPut,
				"/projects/"+url.PathEscape(project)+"/members/"+strconv.FormatInt(existing.ID, 10),
				map[string]any{"role_id": roleID}, nil, http.StatusNotFound); err != nil {
				return err
			}
		}
	}
	// Remove memberships the platform no longer intends - a user removed from a group must lose
	// their pull access, or the "access convergence" claim is only half true. The project owner
	// (Harbor's own admin account) is never a row here, so there is nothing to protect from this.
	for name, m := range haveByName {
		if _, ok := wantByName[name]; ok {
			continue
		}
		if m.Type != "u" {
			continue // a group membership someone added by hand: not ours to remove
		}
		if err := c.do(ctx, http.MethodDelete,
			"/projects/"+url.PathEscape(project)+"/members/"+strconv.FormatInt(m.ID, 10), nil, nil,
			http.StatusNotFound); err != nil {
			return err
		}
	}
	return nil
}

// ensureLocalUser creates the platform's account in Harbor's own user database (local auth mode
// only). The password is a throwaway: the account cannot be used until its owner generates one from
// the portal, which is the whole local-mode credential story.
func (c *Client) ensureLocalUser(ctx context.Context, u registry.DesiredUser) error {
	body := map[string]any{
		"username": u.Username,
		"email":    u.Email,
		"realname": u.Realname,
		"password": randomPassword(),
		"comment":  "Managed by KubeHarbor",
	}
	return c.do(ctx, http.MethodPost, "/users", body, nil, http.StatusConflict, http.StatusForbidden)
}

// ensureSysAdmin makes platform admins registry system admins (and demotes anyone who stopped being
// one), so an admin sees every project without a membership row per cluster.
func (c *Client) ensureSysAdmin(ctx context.Context, u registry.DesiredUser) error {
	id, current, err := c.findUser(ctx, u.Username)
	if err != nil {
		return err
	}
	if current == u.SysAdmin {
		return nil
	}
	return c.do(ctx, http.MethodPut, "/users/"+strconv.FormatInt(id, 10)+"/sysadmin",
		map[string]any{"sysadmin_flag": u.SysAdmin}, nil)
}

func (c *Client) findUser(ctx context.Context, username string) (int64, bool, error) {
	var list []struct {
		ID       int64  `json:"user_id"`
		Username string `json:"username"`
		Admin    bool   `json:"sysadmin_flag"`
	}
	if err := c.do(ctx, http.MethodGet, "/users/search?username="+url.QueryEscape(username), nil, &list); err != nil {
		return 0, false, err
	}
	for _, u := range list {
		if strings.EqualFold(u.Username, username) {
			// The search endpoint omits the admin flag, so read the user back for it.
			var full struct {
				Admin bool `json:"sysadmin_flag"`
			}
			if err := c.do(ctx, http.MethodGet, "/users/"+strconv.FormatInt(u.ID, 10), nil, &full); err != nil {
				return u.ID, u.Admin, nil
			}
			return u.ID, full.Admin, nil
		}
	}
	return 0, false, fmt.Errorf("harbor: user %q not found", username)
}

// SetUserPassword sets one local account's password. Admin-driven, so it needs no old password -
// and the platform never learns or stores the value it just applied beyond the one response that
// carries it back to its owner.
func (c *Client) SetUserPassword(ctx context.Context, username, password string) error {
	id, _, err := c.findUser(ctx, username)
	if err != nil {
		return err
	}
	return c.do(ctx, http.MethodPut, "/users/"+strconv.FormatInt(id, 10)+"/password",
		map[string]any{"new_password": password}, nil)
}

// --- Querier ---------------------------------------------------------------------------------

// Status reports the registry's health, cached briefly so the Registry page does not put a
// round-trip on every load. A failure is a REPORT, not an error: the page renders "unreachable"
// rather than a 500, the same way the health panel treats an unreachable cluster.
func (c *Client) Status(ctx context.Context) registry.Status {
	c.mu.Lock()
	if time.Since(c.statusAt) < statusTTL && c.status.Configured {
		st := c.status
		c.mu.Unlock()
		return st
	}
	c.mu.Unlock()

	st := registry.Status{
		Configured:     true,
		Host:           c.set.Host,
		UIURL:          c.set.UIURL,
		AuthMode:       c.set.AuthMode,
		Mirror:         c.set.Mirror,
		CanSetPassword: c.set.CanSetPasswords(),
	}
	for _, u := range c.set.Upstreams {
		st.Upstreams = append(st.Upstreams, u.Host)
	}
	var health struct {
		Status string `json:"status"`
	}
	if err := c.do(ctx, http.MethodGet, "/health", nil, &health); err != nil {
		st.Message = err.Error()
	} else {
		st.Healthy = strings.EqualFold(health.Status, "healthy")
		if !st.Healthy {
			st.Message = "registry reports " + health.Status
		}
	}
	var info struct {
		Version string `json:"harbor_version"`
	}
	if err := c.do(ctx, http.MethodGet, "/systeminfo", nil, &info); err == nil {
		st.Version = info.Version
	}
	// The mode Harbor is really in, which is not necessarily the one this deployment intends - see
	// registry.Status.AuthMode. Best-effort: /configurations is admin-only, and the production shape
	// for the API's credential is a read-only robot, so a failure here keeps the configured value.
	if mode, err := c.readAuthMode(ctx); err == nil && mode != "" {
		st.AuthMode = mode
		// And the button follows the REAL mode: offering "generate a password" against a directory
		// account cannot work, and hiding it on a Harbor that is actually on its own user database
		// would withhold the only way to get a password out of the platform.
		st.CanSetPassword = mode == registry.AuthLocal && !strings.HasPrefix(c.set.Username, "robot$")
	}

	c.mu.Lock()
	c.status, c.statusAt = st, time.Now()
	c.mu.Unlock()
	return st
}

// readAuthMode reports which identity source the registry is actually using, translated into the
// platform's own vocabulary so the portal renders one set of names. Harbor's modes that the platform
// has no word for (uaa, oidc, http) are returned verbatim rather than forced into local/ldap: an
// operator running Harbor behind an IdP should see that, not be told "local accounts".
func (c *Client) readAuthMode(ctx context.Context) (string, error) {
	var cfg struct {
		AuthMode struct {
			Value string `json:"value"`
		} `json:"auth_mode"`
	}
	if err := c.do(ctx, http.MethodGet, "/configurations", nil, &cfg); err != nil {
		return "", err
	}
	switch v := strings.TrimSpace(cfg.AuthMode.Value); v {
	case "":
		return "", nil
	case "db_auth":
		return registry.AuthLocal, nil
	case "ldap_auth":
		return registry.AuthLDAP, nil
	default:
		return v, nil
	}
}

func (c *Client) Projects(ctx context.Context) ([]registry.Project, error) {
	var list []struct {
		Name       string            `json:"name"`
		RepoCount  int               `json:"repo_count"`
		RegistryID int64             `json:"registry_id"`
		UpdateTime time.Time         `json:"update_time"`
		Metadata   map[string]string `json:"metadata"`
	}
	if err := c.do(ctx, http.MethodGet, "/projects?page_size=100&with_detail=true", nil, &list); err != nil {
		return nil, err
	}
	out := make([]registry.Project, 0, len(list))
	for _, p := range list {
		out = append(out, registry.Project{
			Name:      p.Name,
			Kind:      c.kindOf(p.Name, p.RegistryID != 0),
			Public:    p.Metadata["public"] == "true",
			RepoCount: p.RepoCount,
			UpdatedAt: p.UpdateTime,
			Upstream:  c.upstreamOf(p.Name),
		})
	}
	return out, nil
}

// kindOf classifies a project. Anything the platform did not name is external - shown to admins
// only, and never touched by SyncAccess.
func (c *Client) kindOf(name string, proxied bool) registry.ProjectKind {
	switch {
	case name == c.set.Library():
		return registry.KindLibrary
	case proxied || strings.HasPrefix(name, c.set.ProjectPrefix+"cache-"):
		return registry.KindCache
	case strings.HasPrefix(name, c.set.ProjectPrefix):
		return registry.KindCluster
	}
	return registry.KindExternal
}

func (c *Client) upstreamOf(project string) string {
	for _, u := range c.set.Upstreams {
		if c.set.CacheProject(u) == project {
			return u.Host
		}
	}
	return ""
}

func (c *Client) Repositories(ctx context.Context, project string) ([]registry.Repository, error) {
	return c.repositories(ctx, project)
}

func (c *Client) repositories(ctx context.Context, project string) ([]registry.Repository, error) {
	var list []struct {
		Name          string    `json:"name"`
		ArtifactCount int       `json:"artifact_count"`
		PullCount     int64     `json:"pull_count"`
		UpdateTime    time.Time `json:"update_time"`
	}
	if err := c.do(ctx, http.MethodGet,
		"/projects/"+url.PathEscape(project)+"/repositories?page_size=100", nil, &list,
		http.StatusNotFound); err != nil {
		return nil, err
	}
	out := make([]registry.Repository, 0, len(list))
	for _, r := range list {
		out = append(out, registry.Repository{
			// Harbor returns the fully-qualified "<project>/<name>"; the portal wants the short one.
			Name:          strings.TrimPrefix(r.Name, project+"/"),
			FullName:      r.Name,
			ArtifactCount: r.ArtifactCount,
			PullCount:     r.PullCount,
			UpdatedAt:     r.UpdateTime,
		})
	}
	return out, nil
}

func (c *Client) Artifacts(ctx context.Context, project, repo string) ([]registry.Artifact, error) {
	var list []struct {
		Digest   string    `json:"digest"`
		Size     int64     `json:"size"`
		PushTime time.Time `json:"push_time"`
		Type     string    `json:"type"`
		Tags     []struct {
			Name string `json:"name"`
		} `json:"tags"`
	}
	// The scan overview is deliberately NOT requested (`with_scan_overview`): the Security page reads
	// the trivy-operator inside each cluster, and the registry does not publish a second summary.
	path := "/projects/" + url.PathEscape(project) + "/repositories/" + repoPath(repo) +
		"/artifacts?page_size=100&with_tag=true"
	if err := c.do(ctx, http.MethodGet, path, nil, &list, http.StatusNotFound); err != nil {
		return nil, err
	}
	out := make([]registry.Artifact, 0, len(list))
	for _, a := range list {
		art := registry.Artifact{
			Digest:    a.Digest,
			SizeBytes: a.Size,
			PushedAt:  a.PushTime,
			Type:      a.Type,
		}
		for _, t := range a.Tags {
			art.Tags = append(art.Tags, t.Name)
		}
		out = append(out, art)
	}
	return out, nil
}

// repoPath escapes a repository name for a Harbor path segment. Harbor nests repositories with
// slashes ("cilium/cilium") but takes them as ONE path segment, so the slash must be double-escaped
// - a single url.PathEscape leaves "%2F", which Harbor's router splits on anyway.
func repoPath(repo string) string {
	return strings.ReplaceAll(url.PathEscape(repo), "%2F", "%252F")
}

// roleID maps the platform's role vocabulary onto Harbor's numeric project roles.
func roleID(r registry.Role) int {
	switch r {
	case registry.RoleProjectAdmin:
		return 1
	case registry.RoleDeveloper:
		return 2
	case registry.RoleGuest:
		return 3
	}
	return 3
}

// randomPassword generates a throwaway that satisfies Harbor's complexity rule (8+ characters with
// upper, lower and a digit). Used for a local account at creation, before its owner sets their own.
func randomPassword() string {
	return registry.GeneratePassword()
}
